### ISSUE TITLE
Cant Runing on 64 bit machine,windows 8 64 bit

### ISSUE THREAD

**Issue by danztensai** [OlegKunitsyn/libshout-java#2]
Hi there, I'm trying to test this library using 
 Libshout libshout = new Libshout();
            System.out.println(libshout.getVersion());

but when I run , i got error like this 
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\Danial\Documents\NetBeansProjects\JavaApplication6\target\libshout-java.so: Can't load this .dll (machine code=0x101) on a AMD 64-bit platform
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851)
	at java.lang.Runtime.load0(Runtime.java:795)
	at java.lang.System.load(System.java:1062)
	at com.gmail.kunicins.olegs.libshout.Libshout.<clinit>(Libshout.java:10)
	at javaapplication6.JavaApplication6.main(JavaApplication6.java:27)
Java Result: 1

it seem it cant run on windows :(, how to resolve this, or did u have libshout-java.so which can run on windows 64 bit?

**Comment by OlegKunitsyn** [comment]
Of course, "so" works on Linux, "dll" on Windows which currently not supported.
